### PR TITLE
I create  Logout functionality test cases

### PR DESCRIPTION
**Pull request by msaitture**
I created new feature file which is name logout.feature
I created new step definitions which is name logout_stepdefs
I created logoutpage.java

### CODE REVIEW

**Review by Naim-Akbari — APPROVED** [review]
Well done

**Review by Naim-Akbari — APPROVED** [review]
Well done

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]
merged

**Pull request closed without merging**
